--------------------Imports---------------------------

In [151]:
from PIL import Image
import numpy as np
import pandas as pd
import math
import statistics

----------------------------Managing Data--------------------------------

img = Image.open('sample.jfif')
#<img src = "sample.jfif"/>

In [153]:
imgdata = np.asarray(img)

print(imgdata.shape)
print(imgdata)

(177, 284, 3)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [185 151 178]
  [189 155 182]
  [196 163 190]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [185 151 178]
  [189 155 182]
  [196 163 190]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [185 151 178]
  [189 155 182]
  [196 163 190]]

 ...

 [[242  27  86]
  [242  27  86]
  [242  27  86]
  ...
  [  1   1   1]
  [  0   0   0]
  [ 60  60  60]]

 [[242  27  86]
  [242  27  86]
  [242  27  86]
  ...
  [  1   1   1]
  [  0   0   0]
  [ 60  60  60]]

 [[222  73 113]
  [222  73 113]
  [222  73 113]
  ...
  [ 60  60  60]
  [ 61  61  61]
  [ 95  95  95]]]


In [154]:
newarr = imgdata.reshape(177*3,284)
print(newarr.shape)
print(newarr)

(531, 284)
[[255 255 255 ...  23 255 173]
 [ 10 250 179 ...  54 104 240]
 [ 54 104 240 ... 196 163 190]
 ...
 [222  73 113 ... 197 215 176]
 [197 215 176 ... 131 132  97]
 [131 132  97 ...  95  95  95]]


In [155]:
list1=[]
for i in range(0,281):
    list1.append(newarr[0][i])
print(list1)

[255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 253, 255, 255, 254, 241, 255, 254, 223, 253, 254, 214, 254, 251, 218, 255, 250, 221, 255, 252, 220, 255, 254, 216, 255, 253, 220, 255, 253, 220, 255, 253, 220, 255, 253, 220, 255, 253, 220, 255, 253, 220, 255, 253, 220, 255, 253, 220, 253, 252, 221, 255, 255, 224, 255, 251, 215, 252, 241, 185, 248, 235, 156, 251, 235, 140, 255, 234, 141, 255, 231, 146, 255, 233, 147, 255, 233, 147, 255, 233, 147, 255, 233, 147, 255, 233, 147, 255, 233, 147, 255, 233, 147, 255, 233, 147, 255, 236, 144, 255, 236, 149, 250, 232, 148, 253, 232, 149, 255, 234, 146, 252, 224, 127, 249, 216, 109, 255, 222, 108, 255, 218, 109, 255, 218, 109, 255, 218, 109, 255, 218, 109, 255, 218, 109, 255, 218, 109, 255, 218, 109, 255, 218, 109, 255, 217, 109, 255, 220, 111, 253, 217,

In [156]:
list2=[]
for i in range(0,281):
    list2.append(newarr[1][i])
print(list2)

[10, 250, 179, 25, 253, 176, 18, 253, 176, 18, 253, 176, 18, 253, 176, 18, 253, 176, 18, 253, 176, 18, 253, 176, 18, 253, 176, 18, 255, 178, 24, 242, 176, 17, 230, 178, 68, 253, 136, 40, 246, 145, 41, 255, 137, 55, 236, 153, 31, 251, 139, 53, 247, 143, 44, 247, 143, 44, 247, 143, 44, 247, 143, 44, 247, 143, 44, 247, 143, 44, 247, 143, 44, 247, 143, 44, 241, 145, 45, 255, 143, 46, 250, 140, 43, 239, 150, 60, 235, 138, 70, 242, 112, 63, 252, 112, 61, 243, 119, 55, 244, 115, 58, 244, 115, 58, 244, 115, 58, 244, 115, 58, 244, 115, 58, 244, 115, 58, 244, 115, 58, 244, 115, 58, 239, 119, 59, 255, 110, 57, 235, 120, 55, 242, 111, 55, 238, 116, 65, 241, 136, 91, 242, 86, 73, 239, 88, 81, 240, 86, 74, 240, 86, 74, 240, 86, 74, 240, 86, 74, 240, 86, 74, 240, 86, 74, 240, 86, 74, 240, 86, 74, 236, 90, 77, 245, 82, 73, 245, 85, 73, 235, 92, 75, 238, 88, 74, 246, 78, 77, 238, 88, 87, 221, 110, 99, 241, 28, 86, 240, 28, 86, 240, 28, 86, 239, 30, 87, 239, 30, 87, 238, 31, 87, 239, 32, 88, 237, 32, 88

In [157]:
arr=[]
arr.append(list1)
arr.append(list2)

finalarr=np.transpose(arr)

df = pd.DataFrame(finalarr, columns=['random_1', 'random_2'])
print(df)

     random_1  random_2
0         255        10
1         255       250
2         255       179
3         255        25
4         255       253
..        ...       ...
276       242       104
277       179       240
278         3        54
279       255       104
280       174       240

[281 rows x 2 columns]


----------------------------Functions--------------------------------

In [158]:
def mean(list):
    sum = 0
    count = 0 
    for i in range(0,281):
        sum = sum + list[i]
        count = count + 1
    mean = sum/count
    return mean

In [159]:
def median(list):
    l=len(list)
    sortedlist = sorted(list)
    median = 0
    if l%2==0:
        median = (sortedlist[l//2] + sortedlist[(l//2)+1])//2
        return median
    else:
        median = sortedlist[(l+1)//2]
        return median

In [160]:
def variance(list):
    ps=0
    for i in range(0,281):
        ps = ps + (mean(list)-list[i])**2
    variance = (ps)/(281)
    return variance

In [161]:
def standard_deviation(list):

    sd = math.sqrt(variance(list))
    return sd

In [162]:
def geometric_mean(list):
    l = len(list)
    gm = 1
    for i in range(0,281):
        gm = gm*(list[i])**(1/l)
    return gm

In [163]:
def harmonic_mean(list):
    l = len(list)
    sum = 0
    for i in range(0,281):
        sum = sum + 1/list[i]
    hm = l/sum
    return hm

In [164]:
def covariance(list1,list2):
    prodsum=0
    for i in range(0,281):
        prodsum = prodsum + (mean(list1)-list1[i])*(mean(list2)-list2[i])
    covariance = prodsum/(281-1)
    return covariance

In [165]:
def correlation(list1,list2):
    correlation = covariance(list1,list2)/ (standard_deviation(list1)*standard_deviation(list2))
    return correlation

-------------------Function Calling-------------------------------

In [166]:
#Menu
print("1 --------> Mean")
print("2 --------> Median")
print("3 --------> Variance")
print("4 --------> Standard Deviation")
print("5 --------> Geometric Mean")
print("6 --------> Harmonic Mean")
print("7 --------> Covariance")
print("8 --------> Correlation")
print(" ")
choice = int(input("Enter your choice "))

1 --------> Mean
2 --------> Median
3 --------> Variance
4 --------> Standard Deviation
5 --------> Geometric Mean
6 --------> Harmonic Mean
7 --------> Covariance
8 --------> Correlation
 
Enter your choice 1


In [167]:
if choice == 1:
    print("---------------------------------------------")
    print("Mean using Program!")
    print("---------------------------------------------")
    print("Mean of the first coloumn is: ",mean(list1))
    print("Mean of the second coloumn is: ",mean(list2))
    print(" ")
    print("---------------------------------------------")
    print("Mean using Inbuilt functions!")
    print("---------------------------------------------")
    print("Mean of the first coloumn is: ",np.mean(list1))
    print("Mean of the second coloumn is: ",np.mean(list2))
    
elif choice == 2:
    print("---------------------------------------------")
    print("Median using Program!")
    print("---------------------------------------------")
    print("Median of the first coloumn is: ",median(list1))
    print("Median of the second coloumn is: ",median(list2))
    print(" ")
    print("---------------------------------------------")
    print("Median using Inbuilt functions!")
    print("---------------------------------------------")
    print("Median of the first coloumn is: ",np.median(list1))
    print("Median of the second coloumn is: ",np.median(list2))
    
elif choice == 3:
    print("---------------------------------------------")
    print("Variance using Program!")
    print("---------------------------------------------")
    print("Variance of the first coloumn is: ",variance(list1))
    print("Variance of the second coloumn is: ",variance(list2))
    print(" ")
    print("---------------------------------------------")
    print("Variance using Inbuilt functions!")
    print("---------------------------------------------")
    print("Variance of the first coloumn is: ",np.var(list1))
    print("Variance of the second coloumn is: ",np.var(list2))
    
elif choice == 4:
    print("---------------------------------------------")
    print("Standard Deviation using Program!")
    print("---------------------------------------------")
    print("Standard deviation of the first coloumn is: ",standard_deviation(list1))
    print("Standard deviation of the second coloumn is: ",standard_deviation(list2))
    print(" ")
    print("---------------------------------------------")
    print("Standard Deviation using Inbuilt functions!")
    print("---------------------------------------------")
    print("Standard deviation of the first coloumn is: ",np.std(list1))
    print("Standard deviation of the second coloumn is: ",np.std(list2))
    
elif choice == 5:
    print("---------------------------------------------")
    print("Geometric Mean using Program!")
    print("---------------------------------------------")
    print("Geometric Mean of the first coloumn is: ",geometric_mean(list1))
    print("Geometric Mean of the second coloumn is: ",geometric_mean(list2))
    print(" ")
    print("---------------------------------------------")
    print("Geometric Mean using Inbuilt functions!")
    print("---------------------------------------------")
    print("Geometric Mean of the first coloumn is: ",statistics.geometric_mean(list1))
    print("Geometric Mean of the second coloumn is: ",statistics.geometric_mean(list2))
    
elif choice == 6:
    print("---------------------------------------------")
    print("Harmonic Mean using Program!")
    print("---------------------------------------------")
    print("Harmonic Mean of the first coloumn is: ",harmonic_mean(list1))
    print("Harmonic Mean of the second coloumn is: ",harmonic_mean(list2))
    print(" ")
    print("---------------------------------------------")
    print("Harmonic Mean using Inbuilt functions!")
    print("---------------------------------------------")
    print("Harmonic Mean of the first coloumn is: ",statistics.harmonic_mean(list1))
    print("Harmonic Mean of the second coloumn is: ",statistics.harmonic_mean(list2))
    
elif choice == 7:
    print("---------------------------------------------")
    print("Covariance using Program!")
    print("---------------------------------------------")
    print("Covariance of the data is: ",covariance(list1,list2))
    print(" ")
    print("---------------------------------------------")
    print("Covariance using Inbuilt functions!")
    print("---------------------------------------------")
    print("Covariance of the data is: ",np.cov(list1,list2))
    
elif choice == 8:
    print("---------------------------------------------")
    print("Correlation using Program!")
    print("---------------------------------------------")
    print("Correlation of the data is: ",correlation(list1,list2))
    print(" ")
    print("---------------------------------------------")
    print("Correlation using Inbuilt functions!")
    print("---------------------------------------------")
    print("Correlation of the data is: ",np.corrcoef(list1,list2))

---------------------------------------------
Mean using Program!
---------------------------------------------
Mean of the first coloumn is:  212.72953736654804
Mean of the second coloumn is:  136.3238434163701
 
---------------------------------------------
Mean using Inbuilt functions!
---------------------------------------------
Mean of the first coloumn is:  212.72953736654804
Mean of the second coloumn is:  136.3238434163701
